### ISSUE TITLE
关于数字文件名的排序问题

### ISSUE THREAD

**Issue by Lucerne-Grey** [ArminLau/MangaEpubPacker#4]
在数字文件名的情况下，会出现排序问题，类似1.10.11.12以此类推，导致文件合成epub后顺序错误

**Comment by ArminLau** [comment]
非常感谢你提出这个问题，现在修复后应该可以解决你提出的类似1.jpg，10.jpg，11.jpg的场景问题，但排序这里目前并没有一个完美的解决方案。譬如遇到1-0.jpg，1-1.jpg，2-0.jpg，11-0.jpg类似的场景还是没办法处理，不过通常情况下这类场景出现的情况比较少，作为已知问题暂不做修复

**Comment by Lucerne-Grey** [comment]
感谢作者的修复，这样子已经很解决问题了，感谢
